scan_topic: "/scan"
drive_topic: "/vesc/ackermann_cmd_mux/input/navigation"
side: 1
velocity: 1.0
desired_distance: 0.3
max_steering_angle: 0.34

# Kp: 0.5
# Ki: 0.20
# Kd: 0.05

Kp: 0.8
Ki: 0.2
Kd: 0.03
